<?xml version="1.0" encoding="utf-8"?><Database Name="finalProject" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-7222SDS\MSSQLSERVER1;Initial Catalog=finalProject;Integrated Security=True;Trust Server Certificate=True" SettingsObjectName="final_project.Properties.Settings" SettingsPropertyName="finalProjectConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.course" Member="courses">
    <Type Name="course">
      <Column Name="CourseID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="courseName" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.score" Member="scores">
    <Type Name="score">
      <Column Name="ScoreId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StudentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CourseID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="value" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.student" Member="students">
    <Type Name="student">
      <Column Name="StudentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="gender" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
    </Type>
  </Table>
</Database>